# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gIs5Xay-iBqQvL4AVBv_Knu3CFdfcSst
"""

def jaccard_similarity(file1,file2):
  #spilit texts into sets of words
  set1=set(file1.split())
  set2=set(file2.split())

  intersection=set1.intersection(set2)
  union=set1.union(set2)
  similarity=len(intersection)/len(union)
  return similarity,intersection

File1="file1 history is the sytematic study of the past"
File2="file2 history is the sytematic study of the past this is just for practice"
similarity, common_words=jaccard_similarity(File1,File2)
print(f"similarity:{similarity:.2f}")
print(f"common words:{common_words}")