# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o-1p-rXzhMjPPmGiB7PPaLnZYyYCFnE3
"""

import pandas as pd

phishing_keywords = ["urgent", "password reset", "bank","verify","account suspended"]
emails = pd.read_csv("/content/2401001779-2409001146.csv")
if 'content' in emails.columns:
  emails["is_phishing"] = emails["content"].apply(
      lambda x: any(keyword in str(x).lower for keyword in phishing_keywords)
  )
  emails.to_csv("/content/analysed_emails.csv", index=False)
  print("phishing detection complete.")
else:
  print("Error: 'content' column is missing from the dataset.")

"""/content/email_exercises.csv"""

